# **np.sort**

In [62]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([35,  7, 70,  2, 46, 86, 21, 89, 49, 14, 64, 19, 98, 88, 35])

In [63]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[33, 70, 44, 80],
       [31, 68, 14,  2],
       [67,  8, 28, 77],
       [33, 30, 47, 47],
       [86, 79, 92, 22],
       [54, 12, 25, 58]])

In [64]:
np.sort(a)[::-1]

array([98, 89, 88, 86, 70, 64, 49, 46, 35, 35, 21, 19, 14,  7,  2])

In [4]:
np.sort(b,axis=0)

array([[ 1,  6,  2, 29],
       [ 9, 25, 20, 44],
       [43, 31, 46, 65],
       [57, 73, 49, 70],
       [68, 79, 82, 78],
       [81, 88, 98, 82]])

# **np**.**append**

In [65]:
# code
np.append(a,200)

array([ 35,   7,  70,   2,  46,  86,  21,  89,  49,  14,  64,  19,  98,
        88,  35, 200])

In [66]:
b

array([[33, 70, 44, 80],
       [31, 68, 14,  2],
       [67,  8, 28, 77],
       [33, 30, 47, 47],
       [86, 79, 92, 22],
       [54, 12, 25, 58]])

In [67]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[33.        , 70.        , 44.        , 80.        ,  0.54624386],
       [31.        , 68.        , 14.        ,  2.        ,  0.24866058],
       [67.        ,  8.        , 28.        , 77.        ,  0.3018974 ],
       [33.        , 30.        , 47.        , 47.        ,  0.42380714],
       [86.        , 79.        , 92.        , 22.        ,  0.12742354],
       [54.        , 12.        , 25.        , 58.        ,  0.13128157]])

# **np**.**concatenate**

In [68]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [69]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## **np.unique**

In [71]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [72]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# **np.expand_dims**

In [73]:
# code
a.shape

(15,)

In [74]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [75]:
np.expand_dims(a,axis=1)

array([[35],
       [ 7],
       [70],
       [ 2],
       [46],
       [86],
       [21],
       [89],
       [49],
       [14],
       [64],
       [19],
       [98],
       [88],
       [35]])

# np.where

In [76]:
a

array([35,  7, 70,  2, 46, 86, 21, 89, 49, 14, 64, 19, 98, 88, 35])

In [77]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  5,  7, 10, 12, 13]),)

In [78]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([35,  7,  0,  2, 46,  0, 21,  0, 49, 14,  0, 19,  0,  0, 35])

In [79]:
np.where(a%2 == 0,0,a)

array([35,  7,  0,  0,  0,  0, 21, 89, 49,  0,  0, 19,  0,  0, 35])

# **np.argmax**

In [80]:
# code
a

array([35,  7, 70,  2, 46, 86, 21, 89, 49, 14, 64, 19, 98, 88, 35])

In [81]:
np.argmax(a)

np.int64(12)

In [82]:
b

array([[33, 70, 44, 80],
       [31, 68, 14,  2],
       [67,  8, 28, 77],
       [33, 30, 47, 47],
       [86, 79, 92, 22],
       [54, 12, 25, 58]])

In [83]:
np.argmax(b,axis=0)

array([4, 4, 4, 0])

In [84]:
np.argmax(b,axis=1)

array([3, 1, 3, 2, 2, 3])

In [85]:
# np.argmin
np.argmin(a)

np.int64(3)

# **np.cumsum**

In [86]:
a

array([35,  7, 70,  2, 46, 86, 21, 89, 49, 14, 64, 19, 98, 88, 35])

In [87]:
np.cumsum(a)

array([ 35,  42, 112, 114, 160, 246, 267, 356, 405, 419, 483, 502, 600,
       688, 723])

In [88]:
b

array([[33, 70, 44, 80],
       [31, 68, 14,  2],
       [67,  8, 28, 77],
       [33, 30, 47, 47],
       [86, 79, 92, 22],
       [54, 12, 25, 58]])

In [89]:
np.cumsum(b,axis=1)

array([[ 33, 103, 147, 227],
       [ 31,  99, 113, 115],
       [ 67,  75, 103, 180],
       [ 33,  63, 110, 157],
       [ 86, 165, 257, 279],
       [ 54,  66,  91, 149]])

In [90]:
np.cumsum(b)

array([  33,  103,  147,  227,  258,  326,  340,  342,  409,  417,  445,
        522,  555,  585,  632,  679,  765,  844,  936,  958, 1012, 1024,
       1049, 1107])

In [91]:
# np.cumprod
np.cumprod(a)

array([                  35,                  245,                17150,
                      34300,              1577800,            135690800,
                 2849506800,         253606105200,       12426699154800,
            173973788167200,    11134322442700800,   211552126411315200,
        2285364314599337984, -1802125126063325184, -7734147191087726592])

In [92]:
a

array([35,  7, 70,  2, 46, 86, 21, 89, 49, 14, 64, 19, 98, 88, 35])

# **np.percentile**

In [93]:
a

array([35,  7, 70,  2, 46, 86, 21, 89, 49, 14, 64, 19, 98, 88, 35])

In [94]:
np.percentile(a,50)

np.float64(46.0)

In [95]:
np.median(a)

np.float64(46.0)

# **np.histogram**

In [36]:
# code
a

array([70, 72, 36, 50, 98, 51, 46, 27, 26, 22, 27, 49,  1, 95, 94])

In [37]:
np.histogram(a,bins=[0,50,100])

(array([8, 7]), array([  0,  50, 100]))

# **np.corrcoef**

In [96]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# **np.isin**

In [97]:
# code
a


array([35,  7, 70,  2, 46, 86, 21, 89, 49, 14, 64, 19, 98, 88, 35])

In [98]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([70])

# **np.flip**

In [99]:
# code
a

array([35,  7, 70,  2, 46, 86, 21, 89, 49, 14, 64, 19, 98, 88, 35])

In [100]:
np.flip(a)

array([35, 88, 98, 19, 64, 14, 49, 89, 21, 86, 46,  2, 70,  7, 35])

In [101]:
b

array([[33, 70, 44, 80],
       [31, 68, 14,  2],
       [67,  8, 28, 77],
       [33, 30, 47, 47],
       [86, 79, 92, 22],
       [54, 12, 25, 58]])

In [102]:
np.flip(b,axis=1)

array([[80, 44, 70, 33],
       [ 2, 14, 68, 31],
       [77, 28,  8, 67],
       [47, 47, 30, 33],
       [22, 92, 79, 86],
       [58, 25, 12, 54]])

# **np.put**

In [103]:
# code
a

array([35,  7, 70,  2, 46, 86, 21, 89, 49, 14, 64, 19, 98, 88, 35])

In [104]:
np.put(a,[0,1],[110,530])

# **np.delete**

In [105]:
# code
a

array([110, 530,  70,   2,  46,  86,  21,  89,  49,  14,  64,  19,  98,
        88,  35])

In [106]:
np.delete(a,[0,2,4])

array([530,   2,  86,  21,  89,  49,  14,  64,  19,  98,  88,  35])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [112]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [108]:
np.intersect1d(m,n)

array([3, 4, 5])

In [114]:
np.setdiff1d(n,m)

array([6, 7])

In [115]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [113]:
m[np.in1d(m,1)]

<ipython-input-113-3d5a78555eb5>:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

# **np.clip**

In [116]:
# code
a

array([110, 530,  70,   2,  46,  86,  21,  89,  49,  14,  64,  19,  98,
        88,  35])

In [117]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 70, 25, 46, 75, 25, 75, 49, 25, 64, 25, 75, 75, 35])