### Creating Numpy Arrays

In [69]:
# np.array
import numpy as np
a=np.array([1,2,3,4])
print(type(a))

<class 'numpy.ndarray'>


In [70]:
# 2D and 3D
b = np.array([[1,2,3],[2,3,4]])
print(b)

[[1 2 3]
 [2 3 4]]


In [71]:
c = np.array([[[1,2],[2,3],[4,5],[5,6]]])
print(c)

[[[1 2]
  [2 3]
  [4 5]
  [5 6]]]


In [72]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [73]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [74]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [75]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
# np.random
np.random.random((3,4))

array([[0.63461198, 0.22292109, 0.39186946, 0.37136416],
       [0.61940278, 0.5662009 , 0.41397802, 0.01735563],
       [0.3017358 , 0.8541316 , 0.38611721, 0.02099048]])

In [78]:
# np.linspace
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [79]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [80]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [81]:
# ndim
a3.ndim

3

In [82]:
# shape
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [83]:
# size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [84]:
# itemsize
a3.itemsize

8

In [85]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [86]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [87]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [88]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [89]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [90]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [91]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[63., 38., 87.],
       [41., 58., 64.],
       [22., 52.,  5.]])

In [92]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)

array([ 56826., 114608.,  27840.])

In [93]:
# mean/median/std/var
np.var(a1,axis=1)

array([400.22222222,  94.88888889, 377.55555556])

In [94]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.1673557 ,  0.29636858, -0.82181784],
       [-0.15862267,  0.99287265,  0.92002604],
       [-0.00885131,  0.98662759, -0.95892427]])

In [95]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [96]:
# log and exponents
np.exp(a1)

array([[2.29378316e+27, 3.18559318e+16, 6.07603023e+37],
       [6.39843494e+17, 1.54553894e+25, 6.23514908e+27],
       [3.58491285e+09, 3.83100800e+22, 1.48413159e+02]])

In [97]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[16., 60., 50.],
       [42., 51., 94.]])

### Indexing and Slicing

In [98]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [99]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
a2[1,0]

np.int64(4)

In [102]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [103]:
a3[1,0,1]

np.int64(5)

In [104]:
a3[1,1,0]

np.int64(6)

In [105]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
a1[2:5:2]

array([2, 4])

In [107]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [109]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [110]:
a2[1,::3]

array([4, 7])

In [111]:
a2[0,:]

array([0, 1, 2, 3])

In [112]:
a2[:,2]

array([ 2,  6, 10])

In [113]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [114]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [115]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [116]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [117]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [118]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [119]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [121]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [122]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [123]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [124]:
# reshape
a = np.arange(12).reshape(3,4)

In [125]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [126]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [127]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [128]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [129]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [130]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [132]:
# vertical splitting

In [133]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [134]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]